# ----Removed redundant tasks----
TASK_1:
  EDGE: [5, 4]
  TYPE: "formation_predicate"
  CENTER: [1.8, 1.6]
  EPSILON: 1.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [5, 4]

TASK_2:
  EDGE: [5, 3]
  TYPE: formation_predicate
  CENTER: [0.21955040501426495, 0.24278746001527782]
  EPSILON: 0.2232340942920255
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [5, 3]

TASK_3:
  EDGE: [3, 1]
  TYPE: formation_predicate
  CENTER: [0.21919651517218916, 0.24323246145479507]
  EPSILON: 0.22326313930259536
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [3, 1]

TASK_4:
  EDGE: [1, 2]
  TYPE: formation_predicate
  CENTER: [0.8522667051358438, 0.08172717346747409]
  EPSILON: 0.17609019896184583
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [1, 2]

TASK_5:
  EDGE: [2, 4]
  TYPE: formation_predicate
  CENTER: [0.4509066713687379, 0.9080217640739336]
  EPSILON: 0.18092961974112293
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [2, 4]

#  # phase 2

TASK_6:
  EDGE: [1, 4]
  TYPE: "formation_predicate"
  CENTER: [1.8, 1.8]
  EPSILON: 1.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [170, 170]
  INVOLVED_AGENTS: [1, 4]

TASK_7:
 EDGE: [1, 2]
 TYPE: formation_predicate
 CENTER: [0.7997980743823299, 0.7997980743823297]
 EPSILON: 0.2784058050210902
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [1, 2]

TASK_8:
 EDGE: [2, 4]
 TYPE: formation_predicate
 CENTER: [0.7997980743823296, 0.7997980743823297]
 EPSILON: 0.27840580502109025
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [2, 4]

TASK_9:
  EDGE: [1, 5]
  TYPE: "formation_predicate"
  CENTER: [-1.8, 1.8]
  EPSILON: 1.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [170, 170]
  INVOLVED_AGENTS: [1, 5]

TASK_10:
 EDGE: [1, 3]
 TYPE: formation_predicate
 CENTER: [-0.7997980743823297, 0.7997980743823299]
 EPSILON: 0.27840580502109025
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [1, 3]

TASK_11:
 EDGE: [3, 5]
 TYPE: formation_predicate
 CENTER: [-0.7997980743823297, 0.7997980743823296]
 EPSILON: 0.2784058050210902
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [3, 5]

# # phase 3

TASK_12:
  EDGE: [1, 5]
  TYPE: "formation_predicate"
  CENTER: [-1.0, 1.5]
  EPSILON: 1.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [270, 270]
  INVOLVED_AGENTS: [1, 5]

TASK_13:
 EDGE: [1, 3]
 TYPE: formation_predicate
 CENTER: [-0.8525109962069372, 0.5525452401327409]
 EPSILON: 0.20207751463844267
 TEMP_OP: AlwaysOperator
 INTERVAL: [270, 270]
 INVOLVED_AGENTS: [1, 3]

TASK_14:
 EDGE: [3, 5]
 TYPE: formation_predicate
 CENTER: [-0.11212465603064474, 0.7019567820446424]
 EPSILON: 0.30262204531738546
 TEMP_OP: AlwaysOperator
 INTERVAL: [270, 270]
 INVOLVED_AGENTS: [3, 5]

TASK_15:
  EDGE: [2, 6]
  TYPE: "formation_predicate"
  CENTER: [0.0, -1.0]
  EPSILON: 1.0
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [260, 270]
  INVOLVED_AGENTS: [2, 6]

TASK_16:
 EDGE: [2, 1]
 TYPE: formation_predicate
 CENTER: [-0.7539127923925574, -1.260494198224531]
 EPSILON: 0.190950920866441
 TEMP_OP: AlwaysOperator
 INTERVAL: [260, 270]
 INVOLVED_AGENTS: [2, 1]

TASK_17:
 EDGE: [1, 6]
 TYPE: formation_predicate
 CENTER: [0.5382377050604792, 0.19683727570978818]
 EPSILON: 0.30412005390211555
 TEMP_OP: AlwaysOperator
 INTERVAL: [260, 270]
 INVOLVED_AGENTS: [1, 6]





# # ----Removed redundant tasks----
# TASK_1:
#   EDGE: [5, 4]
#   TYPE: "formation_predicate"
#   CENTER: [1.8, 1.6]
#   EPSILON: 1.8
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [5, 4]

# TASK_2:
#   EDGE: [5, 3]
#   TYPE: formation_predicate
#   CENTER: [0.21955040501426495, 0.24278746001527782]
#   EPSILON: 0.2232340942920255
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [5, 3]

# TASK_3:
#   EDGE: [3, 1]
#   TYPE: formation_predicate
#   CENTER: [0.21919651517218916, 0.24323246145479507]
#   EPSILON: 0.22326313930259536
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [3, 1]

# TASK_4:
#   EDGE: [1, 2]
#   TYPE: formation_predicate
#   CENTER: [0.8522667051358438, 0.08172717346747409]
#   EPSILON: 0.17609019896184583
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [1, 2]

# TASK_5:
#   EDGE: [2, 4]
#   TYPE: formation_predicate
#   CENTER: [0.4509066713687379, 0.9080217640739336]
#   EPSILON: 0.18092961974112293
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [2, 4]

# #  # phase 2

# TASK_6:
#   EDGE: [1, 4]
#   TYPE: "formation_predicate"
#   CENTER: [1.8, 1.8]
#   EPSILON: 1.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [170, 170]
#   INVOLVED_AGENTS: [1, 4]

# TASK_7:
#  EDGE: [1, 2]
#  TYPE: formation_predicate
#  CENTER: [0.7997980743823299, 0.7997980743823297]
#  EPSILON: 0.2784058050210902
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [1, 2]

# TASK_8:
#  EDGE: [2, 4]
#  TYPE: formation_predicate
#  CENTER: [0.7997980743823296, 0.7997980743823297]
#  EPSILON: 0.27840580502109025
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [2, 4]

# TASK_9:
#   EDGE: [1, 5]
#   TYPE: "formation_predicate"
#   CENTER: [-1.8, 1.8]
#   EPSILON: 1.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [170, 170]
#   INVOLVED_AGENTS: [1, 5]

# TASK_10:
#  EDGE: [1, 3]
#  TYPE: formation_predicate
#  CENTER: [-0.7997980743823297, 0.7997980743823299]
#  EPSILON: 0.27840580502109025
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [1, 3]

# TASK_11:
#  EDGE: [3, 5]
#  TYPE: formation_predicate
#  CENTER: [-0.7997980743823297, 0.7997980743823296]
#  EPSILON: 0.2784058050210902
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [3, 5]

# # # phase 3

# TASK_12:
#   EDGE: [1, 5]
#   TYPE: "formation_predicate"
#   CENTER: [-1.0, 1.5]
#   EPSILON: 1.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [270, 270]
#   INVOLVED_AGENTS: [1, 5]

# TASK_13:
#  EDGE: [1, 3]
#  TYPE: formation_predicate
#  CENTER: [-0.8525109962069372, 0.5525452401327409]
#  EPSILON: 0.20207751463844267
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [270, 270]
#  INVOLVED_AGENTS: [1, 3]

# TASK_14:
#  EDGE: [3, 5]
#  TYPE: formation_predicate
#  CENTER: [-0.11212465603064474, 0.7019567820446424]
#  EPSILON: 0.30262204531738546
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [270, 270]
#  INVOLVED_AGENTS: [3, 5]

# TASK_15:
#   EDGE: [2, 6]
#   TYPE: "formation_predicate"
#   CENTER: [0.0, -1.0]
#   EPSILON: 1.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [260, 270]
#   INVOLVED_AGENTS: [2, 6]

# TASK_16:
#  EDGE: [2, 1]
#  TYPE: formation_predicate
#  CENTER: [-0.7539127923925574, -1.260494198224531]
#  EPSILON: 0.190950920866441
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [260, 270]
#  INVOLVED_AGENTS: [2, 1]

# TASK_17:
#  EDGE: [1, 6]
#  TYPE: formation_predicate
#  CENTER: [0.5382377050604792, 0.19683727570978818]
#  EPSILON: 0.30412005390211555
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [260, 270]
#  INVOLVED_AGENTS: [1, 6]









