# ----Removed redundant tasks----
TASK_1:
  EDGE: [5, 4]
  TYPE: "formation_predicate"
  CENTER: [1.8, 1.6]
  EPSILON: 1.0
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [5, 4]

TASK_2:
  EDGE: [5, 3]
  TYPE: formation_predicate
  CENTER: [0.2707589669030826, 0.3775583206866954]
  EPSILON: 0.12960081546691857
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [5, 3]

TASK_3:
  EDGE: [3, 1]
  TYPE: formation_predicate
  CENTER: [0.8863853015080271, 0.11561306995571706]
  EPSILON: 0.11484529208641826
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [3, 1]

TASK_4:
  EDGE: [1, 2]
  TYPE: formation_predicate
  CENTER: [0.12022511531856145, 0.13071413125216502]
  EPSILON: 0.11968697588691492
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [1, 2]

TASK_5:
  EDGE: [2, 4]
  TYPE: formation_predicate
  CENTER: [0.4918640313494004, 0.9329417699351513]
  EPSILON: 0.11650967861863286
  TEMP_OP: AlwaysOperator
  INTERVAL: [80, 80]
  INVOLVED_AGENTS: [2, 4]

#  # phase 2

TASK_6:
  EDGE: [1, 4]
  TYPE: "formation_predicate"
  CENTER: [1.8, 1.8]
  EPSILON: 1.0
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [170, 170]
  INVOLVED_AGENTS: [1, 4]

TASK_7:
 EDGE: [1, 2]
 TYPE: formation_predicate
 CENTER: [0.8547233633214096, 0.8547233628685093]
 EPSILON: 0.1951693214830126
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [1, 2]

TASK_8:
 EDGE: [2, 4]
 TYPE: formation_predicate
 CENTER: [0.8547233633215456, 0.8547233628887688]
 EPSILON: 0.1951693214932002
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [2, 4]

TASK_9:
  EDGE: [1, 5]
  TYPE: "formation_predicate"
  CENTER: [-1.8, 1.8]
  EPSILON: 1.0
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [170, 170]
  INVOLVED_AGENTS: [1, 5]

TASK_10:
 EDGE: [1, 3]
 TYPE: formation_predicate
 CENTER: [-0.8547233617196534, 0.8547233617194983]
 EPSILON: 0.19516932232794032
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [1, 3]

TASK_11:
 EDGE: [3, 5]
 TYPE: formation_predicate
 CENTER: [-0.8547233617196452, 0.8547233617194941]
 EPSILON: 0.19516932232798434
 TEMP_OP: AlwaysOperator
 INTERVAL: [170, 170]
 INVOLVED_AGENTS: [3, 5]

# # phase 3

TASK_12:
  EDGE: [1, 5]
  TYPE: "formation_predicate"
  CENTER: [-1.0, 1.5]
  EPSILON: 0.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [270, 270]
  INVOLVED_AGENTS: [1, 5]

TASK_13:
 EDGE: [1, 3]
 TYPE: formation_predicate
 CENTER: [-0.8434248113841768, 0.5840931164778397]
 EPSILON: 0.09532986564776494
 TEMP_OP: AlwaysOperator
 INTERVAL: [270, 270]
 INVOLVED_AGENTS: [1, 3]

TASK_14:
 EDGE: [3, 5]
 TYPE: formation_predicate
 CENTER: [-0.15197545108756566, 0.8889035344645416]
 EPSILON: 0.1035217763432144
 TEMP_OP: AlwaysOperator
 INTERVAL: [270, 270]
 INVOLVED_AGENTS: [3, 5]

TASK_15:
  EDGE: [2, 6]
  TYPE: "formation_predicate"
  CENTER: [0.0, -1.0]
  EPSILON: 0.5
  TEMP_OP: "AlwaysOperator"
  INTERVAL: [260, 270]
  INVOLVED_AGENTS: [2, 6]

TASK_16:
 EDGE: [2, 1]
 TYPE: formation_predicate
 CENTER: [-0.7078048982861667, -1.227572640030989]
 EPSILON: 0.09355344781331103
 TEMP_OP: AlwaysOperator
 INTERVAL: [260, 270]
 INVOLVED_AGENTS: [2, 1]

TASK_17:
 EDGE: [1, 6]
 TYPE: formation_predicate
 CENTER: [0.6837081732483519, 0.21984470020896446]
 EPSILON: 0.10423021786214216
 TEMP_OP: AlwaysOperator
 INTERVAL: [260, 270]
 INVOLVED_AGENTS: [1, 6]





# # ----Removed redundant tasks----
# TASK_1:
#   EDGE: [5, 4]
#   TYPE: "formation_predicate"
#   CENTER: [1.8, 1.6]
#   EPSILON: 1.0
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [5, 4]

# TASK_2:
#   EDGE: [5, 3]
#   TYPE: formation_predicate
#   CENTER: [0.2707589669030826, 0.3775583206866954]
#   EPSILON: 0.12960081546691857
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [5, 3]

# TASK_3:
#   EDGE: [3, 1]
#   TYPE: formation_predicate
#   CENTER: [0.8863853015080271, 0.11561306995571706]
#   EPSILON: 0.11484529208641826
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [3, 1]

# TASK_4:
#   EDGE: [1, 2]
#   TYPE: formation_predicate
#   CENTER: [0.12022511531856145, 0.13071413125216502]
#   EPSILON: 0.11968697588691492
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [1, 2]

# TASK_5:
#   EDGE: [2, 4]
#   TYPE: formation_predicate
#   CENTER: [0.4918640313494004, 0.9329417699351513]
#   EPSILON: 0.11650967861863286
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [80, 80]
#   INVOLVED_AGENTS: [2, 4]

# TASK_6:
#   EDGE: [2, 6]
#   TYPE: "epsilon_position_closeness_predicate"
#   CENTER: [0.0, 0.0]
#   EPSILON: 0.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [60, 80]
#   INVOLVED_AGENTS: [2, 6]

# TASK_7:
#   EDGE: [2, 1]
#   TYPE: epsilon_position_closeness_predicate
#   CENTER: [-0.031071072197047852, -0.033691841898981625]
#   EPSILON: 0.270590123271231
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [60, 80]
#   INVOLVED_AGENTS: [2, 1]

# TASK_8:
#   EDGE: [1, 6]
#   TYPE: epsilon_position_closeness_predicate
#   CENTER: [0.029450534919349805, 0.0313991095239478]
#   EPSILON: 0.028941380045167775
#   TEMP_OP: AlwaysOperator
#   INTERVAL: [60, 80]
#   INVOLVED_AGENTS: [1, 6]

# #  # phase 2

# TASK_9:
#   EDGE: [1, 4]
#   TYPE: "formation_predicate"
#   CENTER: [1.8, 1.8]
#   EPSILON: 1.0
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [170, 170]
#   INVOLVED_AGENTS: [1, 4]

# TASK_10:
#  EDGE: [1, 2]
#  TYPE: formation_predicate
#  CENTER: [0.8547233633214096, 0.8547233628685093]
#  EPSILON: 0.1951693214830126
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [1, 2]

# TASK_11:
#  EDGE: [2, 4]
#  TYPE: formation_predicate
#  CENTER: [0.8547233633215456, 0.8547233628887688]
#  EPSILON: 0.1951693214932002
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [2, 4]

# TASK_12:
#   EDGE: [1, 5]
#   TYPE: "formation_predicate"
#   CENTER: [-1.8, 1.8]
#   EPSILON: 1.0
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [170, 170]
#   INVOLVED_AGENTS: [1, 5]

# TASK_13:
#  EDGE: [1, 3]
#  TYPE: formation_predicate
#  CENTER: [-0.8547233617196534, 0.8547233617194983]
#  EPSILON: 0.19516932232794032
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [1, 3]

# TASK_14:
#  EDGE: [3, 5]
#  TYPE: formation_predicate
#  CENTER: [-0.8547233617196452, 0.8547233617194941]
#  EPSILON: 0.19516932232798434
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [170, 170]
#  INVOLVED_AGENTS: [3, 5]

# # # phase 3

# TASK_15:
#   EDGE: [1, 5]
#   TYPE: "formation_predicate"
#   CENTER: [-1.0, 1.5]
#   EPSILON: 0.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [270, 270]
#   INVOLVED_AGENTS: [1, 5]

# TASK_16:
#  EDGE: [1, 3]
#  TYPE: formation_predicate
#  CENTER: [-0.8434248113841768, 0.5840931164778397]
#  EPSILON: 0.09532986564776494
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [270, 270]
#  INVOLVED_AGENTS: [1, 3]

# TASK_17:
#  EDGE: [3, 5]
#  TYPE: formation_predicate
#  CENTER: [-0.15197545108756566, 0.8889035344645416]
#  EPSILON: 0.1035217763432144
#  TEMP_OP: AlwaysOperator

#  INTERVAL: [270, 270]
#  INVOLVED_AGENTS: [3, 5]

# TASK_18:
#   EDGE: [2, 6]
#   TYPE: "formation_predicate"
#   CENTER: [0.0, -1.0]
#   EPSILON: 0.5
#   TEMP_OP: "AlwaysOperator"
#   INTERVAL: [260, 270]
#   INVOLVED_AGENTS: [2, 6]

# TASK_19:
#  EDGE: [2, 1]
#  TYPE: formation_predicate
#  CENTER: [-0.7078048982861667, -1.227572640030989]
#  EPSILON: 0.09355344781331103
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [260, 270]
#  INVOLVED_AGENTS: [2, 1]

# TASK_20:
#  EDGE: [1, 6]
#  TYPE: formation_predicate
#  CENTER: [0.6837081732483519, 0.21984470020896446]
#  EPSILON: 0.10423021786214216
#  TEMP_OP: AlwaysOperator
#  INTERVAL: [260, 270]
#  INVOLVED_AGENTS: [1, 6]








